@echo off
REM %1 generator

cd %BDIR%
cmake -G%1 -D ASSIMP_BUILD_ASSIMP_TOOLS:BOOL=OFF -D ASSIMP_BUILD_TESTS:BOOL=OFF -D ASSIMP_INSTALL_PDB:BOOL=OFF -D LIBRARY_SUFFIX:STRING= ../ || goto :nocmake
exit

:nocmake
color 0C
echo.
echo.
echo ERROR WITH CMAKE. CMAKE PROBABLY NOT IN PATH.
echo THE PROJECT MIGHT HAVE INVALID FILES NOW.
PAUSE